
## Global Proteomics

```{r prot-camera}
mem <- w
sex_i <- "Female"

keep <- fData(eset_list[[sex_i]])[["ome"]] == "PROT_GN"
mem <- mem[keep, ]

# Convert proteins to gene symbols
rownames(mem) <- fData(eset_list[[sex_i]])[["featureName2"]][keep]

PROT_GN_CMEANS_CAMERA <- cameraPR(statistic = mem, 
                                  index = prot_GN_gene_sets, 
                                  inter.gene.cor = 0.01,
                                  use.ranks = TRUE, # non-parametric
                                  adjust.globally = TRUE, 
                                  alternative = "greater", # upper-tail tests
                                  min.size = 5L) %>% 
  rename(Cluster = Contrast, PAdj = FDR) %>% 
  mutate(logPAdj = -log10(PAdj)) %>% 
  left_join(SET_TO_ID, by = "GeneSet") %>% 
  mutate(NRatio = round(NGenes / NGenesHuman, digits = 3)) %>% 
  # Reorder columns
  select(Cluster, GeneSetID, GeneSet, GeneSetShort,
         NGenes, NGenesHuman, NRatio, Direction, logPAdj, PValue, PAdj)

head(PROT_GN_CMEANS_CAMERA)
```

```{r}
# Number of gene sets significantly localizing to each cluster
with(filter(PROT_GN_CMEANS_CAMERA, PAdj < 0.05), table(Cluster))
```

```{r prot-ORA}
prot_cluster <- cluster[keep]

# Convert metabolites to RefMet IDs
names(prot_cluster) <- fData(eset_list[[sex_i]])[["featureName2"]][keep]
prot_cluster <- prot_cluster[order(prot_cluster, decreasing = FALSE)]
prot_cluster_list <- split(x = names(prot_cluster),
                           f = factor(prot_cluster,
                                      levels = as.character(unique(prot_cluster))))

PROT_GN_CMEANS_ORA <- run_cluster_ORA(cluster_list = prot_cluster_list,
                                      gene_sets = prot_GN_gene_sets,
                                      min_size = 5L) %>%
  rename(GeneSet = Set) %>% 
  left_join(SET_TO_ID, by = "GeneSet")

head(PROT_GN_CMEANS_ORA)
```


## Transcriptomics

```{r prot-camera}
mem <- w
sex_i <- "Female"

keep <- fData(eset_list[[sex_i]])[["ome"]] == "TRNSCRPT_GN"
mem <- mem[keep, ]

# Convert proteins to gene symbols
rownames(mem) <- fData(eset_list[[sex_i]])[["featureName2"]][keep]

TRNSCRPT_GN_CMEANS_CAMERA <- cameraPR(statistic = mem, 
                                      index = trnscrpt_GN_gene_sets, 
                                      inter.gene.cor = 0.01,
                                      use.ranks = TRUE, # non-parametric
                                      adjust.globally = TRUE, 
                                      alternative = "greater", # upper-tail tests
                                      min.size = 5L) %>% 
  rename(Cluster = Contrast, PAdj = FDR) %>% 
  mutate(logPAdj = -log10(PAdj)) %>% 
  left_join(SET_TO_ID, by = "GeneSet") %>% 
  mutate(NRatio = round(NGenes / NGenesHuman, digits = 3)) %>% 
  # Reorder columns
  select(Cluster, GeneSetID, GeneSet, GeneSetShort,
         NGenes, NGenesHuman, NRatio, Direction, logPAdj, PValue, PAdj)

head(TRNSCRPT_GN_CMEANS_CAMERA)
```

```{r}
# Number of gene sets significantly localizing to each cluster
with(filter(TRNSCRPT_GN_CMEANS_CAMERA, PAdj < 0.05), table(Cluster))
```

```{r prot-ORA}
trnscrpt_cluster <- cluster[keep]

# Convert metabolites to RefMet IDs
names(trnscrpt_cluster) <- fData(eset_list[[sex_i]])[["featureName2"]][keep]
trnscrpt_cluster <- trnscrpt_cluster[order(trnscrpt_cluster, decreasing = FALSE)]
trnscrpt_cluster_list <- split(x = names(trnscrpt_cluster),
                               f = factor(trnscrpt_cluster,
                                          levels = as.character(unique(trnscrpt_cluster))))

TRNSCRPT_GN_CMEANS_ORA <- run_cluster_ORA(cluster_list = trnscrpt_cluster_list,
                                          gene_sets = trnscrpt_GN_gene_sets,
                                          min_size = 5L) %>%
  rename(GeneSet = Set) %>% 
  left_join(SET_TO_ID, by = "GeneSet")

head(TRNSCRPT_GN_CMEANS_ORA)
```



## Metabolomics/Lipidomics

```{r metab-camera}
mem <- w

keep <- fData(eset_list[[sex_i]])[["ome"]] == "METAB_GN"
mem <- mem[keep, ]

# Convert metabolites to RefMet IDs
rownames(mem) <- fData(eset_list[[sex_i]])[["featureName2"]][keep]

METAB_GN_CMEANS_CAMERA <- cameraPR(statistic = mem, 
                                   index = metab_GN_refmet_sets,  
                                   inter.gene.cor = 0.01,
                                   use.ranks = TRUE, # non-parametric
                                   adjust.globally = TRUE,
                                   alternative = "greater", # upper-tail tests
                                   min.size = 5L) %>% 
  rename(Cluster = Contrast, Subclass = GeneSet, 
         NMetabolites = NGenes, PAdj = FDR) %>% 
  mutate(logPAdj = -log10(PAdj)) %>% 
  relocate(logPAdj, .before = PValue)

head(METAB_GN_CMEANS_CAMERA)
```

```{r}
# Number of RefMet subclasses significantly localizing to each cluster
with(filter(METAB_GN_CMEANS_CAMERA, PAdj < 0.05), table(Cluster))
```


```{r metab-ORA}
metab_cluster <- cluster[keep]

# Convert metabolites to RefMet IDs
names(metab_cluster) <- fData(eset_list[[sex_i]])[["featureName2"]][keep]
metab_cluster <- metab_cluster[order(metab_cluster, decreasing = FALSE)]
metab_cluster_list <- split(x = names(metab_cluster),
                            f = factor(metab_cluster,
                                       levels = as.character(unique(metab_cluster))))

METAB_GN_CMEANS_ORA <- run_cluster_ORA(cluster_list = metab_cluster_list,
                                       gene_sets = metab_GN_refmet_sets,
                                       min_size = 5L) %>%
  rename(Subclass = Set)

head(METAB_GN_CMEANS_ORA)
```



## Plot Top Terms by Cluster

```{r bubble-heatmaps, eval=save_plots}
## Bubble heatmaps of tests for gene set localization
cmeans_camera_res <- list("PROT_GN" = PROT_GN_CMEANS_CAMERA,
                          "TRNSCRPT_GN" = TRNSCRPT_GN_CMEANS_CAMERA,
                          "METAB_GN" = METAB_GN_CMEANS_CAMERA)

for (ome_i in names(cmeans_camera_res)) {
  # for (sex_i in c("Female", "Male")) {
  sex_i <- "Female"
  message(paste(ome_i, sex_i))
  
  xi <- cmeans_camera_res[[ome_i]] %>% 
    # filter(Sex == sex_i) %>% 
    rename(any_of(c("Set" = "GeneSet", "Set" = "Subclass")))
  
  if (ome_i != "METAB_GN") {
    xi <- filter(xi, grepl("^GOBP_", Set)) # GOBP only
  }
  
  # Select the top 6 terms by cluster
  top_terms <- xi %>% 
    filter(PAdj < 0.05) %>% 
    slice_min(PValue, n = 8L, by = Cluster) %>%
    pull(Set) %>% 
    unique()
  
  xi <- filter(xi, Set %in% top_terms) %>% 
    mutate(logP = -log10(PValue))
  
  # Dynamic heatmap height. Each cell of the heatmap is 14 pt, by default
  height <- convertUnit(length(top_terms) * unit(15, "pt"), "in")
  height <- max(as.numeric(height) + 0.2, 4)
  
  set_column <- ifelse(grepl("^METAB", ome_i), "Set", "GeneSetShort")
  
  # Dynamic heatmap width
  row_label_width <- ComplexHeatmap::max_text_width(xi[[set_column]])
  row_label_width <- convertUnit(row_label_width, "in")
  
  width <- convertUnit(nlevels(xi$Cluster) * unit(15, "pt"), "in")
  width <- as.numeric(width + row_label_width) + 2.5
  
  enrichmap(x = xi,
            plot_sig_only = FALSE,
            n_top = Inf, # plot all terms
            statistic_column = "logP",
            set_column = set_column,
            padj_column = "PAdj",
            padj_legend_title = "BH Adjusted\nP-Value",
            contrast_column = "Cluster",
            heatmap_args = list(
              rect_gp = gpar(fill = "white", col = "grey85"),
              heatmap_legend_param = list(
                title = latex2exp::TeX(
                  "$\\bf{$-$log_{10}(P$-$Value)}$")
              ),
              clustering_distance_rows = "pearson",
              column_names_side = "top"#,
              # column_split = rep(c("", " ", "  ", "   ", "    "), 
              #                    each = 6L) %>% 
              #   factor(levels = unique(.))
            ),
            color = c("white", "#503080"),
            # filename = "plots/test_camera.png",
            filename = file.path("..", "plots", "fuzzy_cmeans",
                                 sprintf("%s-%s-cmeans_CAMERA.png",
                                         ome_i, tolower(sex_i))),
            save_args = list("res" = 100, "dpi" = 200),
            height = height, width = width)
}
```



```{r}
layer_fun <- function(j, i, x, y, w, h, f) {
  # Cell background
  grid.rect(x = x, y = y, width = w, height = h,
            gp = gpar(col = heatmap_args[["rect_gp"]][["col"]],
                      fill = ifelse(
                        is.na(pindex(padj_mat, i, j)),
                        heatmap_args[["na_col"]], # black
                        ifelse(pindex(padj_mat, i, j) < padj_cutoff,
                               padj_fill, # grey
                               heatmap_args[["rect_gp"]][["fill"]]) # white
                      )
            ))
  
  # Matrix of bubble diameters (optionally scaled to row or column max)
  dmat <- -log10(padj_mat)
  
  if (scale_by == "max") {
    # Scale bubbles relative to global max
    for (method in c("CAMERA", "ORA")) {
      idx <- grep(method, colnames(dmat))
      dmat[, idx] <- dmat[, idx] / max(dmat[, idx], na.rm = TRUE)
    }
    
  } else {
    # Scale bubbles relative to row or column max
    margin <- 1L + (scale_by == "column")
    for (method in c("CAMERA-PR", "ORA")) {
      idx <- grep(method, colnames(dmat))
      dmat[, idx] <- sweep(dmat[, idx], MARGIN = margin,
                           apply(dmat[, idx], MARGIN = margin,
                                 max, na.rm = TRUE),
                           FUN = "/")
    }
  }
  
  # Limits on bubble diameters
  r_min <- 0.20 # only applies to significant adjusted p-values
  r_max <- 0.95 # upper limit because a black border is added to the bubbles
  dmat <- ifelse(padj_mat < padj_cutoff,
                 dmat * (r_max - r_min) + r_min,
                 dmat * r_max)
  
  # Draw bubbles
  grid.circle(
    x = x, y = y,
    r = pindex(dmat, i, j) / 2 * cell_size,
    # Significant bubbles get a black outline to separate from padj_fill
    gp = gpar(col = ifelse(pindex(padj_mat, i, j) < padj_cutoff,
                           "black", NA),
              fill = f)
  )
}
```


```{r}
## Bubble heatmaps of tests for gene set localization
cmeans_res <- list(
  "CAMERA-PR" = list("PROT_GN" = PROT_GN_CMEANS_CAMERA,
                     "TRNSCRPT_GN" = TRNSCRPT_GN_CMEANS_CAMERA,
                     "METAB_GN" = METAB_GN_CMEANS_CAMERA),
  "ORA" = list("PROT_GN" = PROT_GN_CMEANS_ORA,
               "TRNSCRPT_GN" = TRNSCRPT_GN_CMEANS_ORA,
               "METAB_GN" = METAB_GN_CMEANS_ORA)
) %>%
  purrr::list_transpose() %>% 
  lapply(function(xi) {
    data.table::rbindlist(xi, fill = TRUE, idcol = "method") %>% 
      mutate(method = factor(method, levels = c("CAMERA-PR", "ORA")),
             Cluster = paste(method, Cluster),
             Cluster = factor(Cluster, levels = unique(Cluster)))
  })

for (ome_i in names(cmeans_res)) {
  # for (sex_i in c("Female", "Male")) {
  sex_i <- "Female"
  message(paste(ome_i, sex_i))
  
  xi <- cmeans_res[[ome_i]] %>% 
    # filter(Sex == sex_i) %>% 
    rename(any_of(c("Set" = "GeneSet", "Set" = "Subclass"))) %>% 
    mutate(Cluster2 = sub(".* ", "", Cluster),
           Cluster2 = factor(Cluster2, levels = unique(Cluster2)))
  
  if (ome_i != "METAB_GN") {
    xi <- filter(xi, grepl("^GOBP", Set)) # GOBP only
  }
  
  # Select the top 6 terms by cluster
  top_terms <- xi %>% 
    filter(PAdj < 0.05) %>% 
    slice_min(PValue, n = 6L, by = c(method, Cluster)) %>%
    pull(Set) %>% 
    unique()
  
  xi <- filter(xi, Set %in% top_terms) %>% 
    mutate(logP = -log10(PValue))
  
  # Dynamic heatmap height. Each cell of the heatmap is 14 pt, by default
  height <- convertUnit(length(top_terms) * unit(15, "pt"), "in")
  height <- max(as.numeric(height) + 0.2, 4)
  
  set_column <- ifelse(grepl("^METAB", ome_i), "Set", "GeneSetShort")
  
  # Dynamic heatmap width
  row_label_width <- ComplexHeatmap::max_text_width(xi[[set_column]])
  row_label_width <- convertUnit(row_label_width, "in")
  
  width <- convertUnit(nlevels(xi$Cluster) * unit(15, "pt"), "in")
  width <- as.numeric(width + row_label_width) + 2.5
  
  foo <- distinct(xi, method, Cluster, Cluster2) %>% 
    arrange(method, Cluster)
  
  enrichmap(x = xi,
            plot_sig_only = FALSE,
            n_top = Inf, # plot all terms
            statistic_column = "logP",
            set_column = set_column,
            padj_column = "PAdj",
            padj_legend_title = "BH Adjusted\nP-Value",
            contrast_column = "Cluster",
            heatmap_args = list(
              layer_fun = layer_fun,
              column_split = foo$method,
              column_labels = foo$Cluster2,
              rect_gp = gpar(fill = "white", col = "grey85"),
              heatmap_legend_param = list(
                title = latex2exp::TeX(
                  "$\\bf{$-$log_{10}(P$-$Value)}$")
              ),
              clustering_distance_rows = "pearson",
              column_names_side = "top",
              # column_names_rot = 0,
              # column_names_centered = TRUE,
              column_title_gp = gpar(fontsize = unit(16, "pt"),#unit(9, "pt"),
                                     fontface = "bold")
            ),
            color = c("white", "#503080"),
            filename = file.path("..", "plots", "fuzzy_cmeans",
                                 sprintf("%s-%s-cmeans_combined.png",
                                         ome_i, tolower(sex_i))),
            height = height, width = width)
  # }
}
```


Splicing Figures

```{r}
TRNSCRPT_SPLICING_VL_CAMERA = read.csv(
  file.path(here(),
            "Figures",
            "Splicing",
            "data",
            "VL_CAMERA.csv")
) %>%
  mutate(Contrast = "Vastus")

TRNSCRPT_SPLICING_GN_CAMERA = read.csv(
  file.path(here(),
            "Figures",
            "Splicing",
            "data",
            "GN_CAMERA.csv")
) %>%
  mutate(Contrast = "Gastroc")

Splicing_muscles = rbind(TRNSCRPT_SPLICING_VL_CAMERA, 
                         TRNSCRPT_SPLICING_GN_CAMERA)

# Select the top 6 terms by cluster
top_terms <- Splicing_muscles %>% 
  filter(PAdj < 0.05) %>% 
  group_by(Contrast) %>%
  slice_min(PValue, n = 10L) %>%
  ungroup() %>%
  pull(Set) %>% 
  unique()

Splicing_muscles <- filter(Splicing_muscles, Set %in% top_terms) %>% 
  mutate(logP = -log10(PValue))

# Dynamic heatmap height. Each cell of the heatmap is 14 pt, by default
height <- convertUnit(length(top_terms) * unit(20, "pt"), "in")
height <- max(as.numeric(height) + 0.2, 4)

# Dynamic heatmap width
row_label_width <- ComplexHeatmap::max_text_width(Splicing_muscles[["Set"]])
row_label_width <- convertUnit(row_label_width, "in")

width <- convertUnit(15 * unit(15, "pt"), "in")
width <- as.numeric(width + row_label_width) + 2.5

enrichmap(x = Splicing_muscles,
          plot_sig_only = FALSE,
          n_top = Inf, # plot all terms
          statistic_column = "logP",
          set_column = "Set",
          padj_column = "PAdj",
          padj_legend_title = "BH Adjusted\nP-Value",
          contrast_column = "Contrast",
          heatmap_args = list(
            cluster_rows = FALSE,
            rect_gp = gpar(fill = "white", col = "grey85"),
            heatmap_legend_param = list(
              title = latex2exp::TeX(
                "$\\bf{$-$log_{10}(P$-$Value)}$")
            ),
            clustering_distance_rows = "pearson",
            column_names_side = "top",
            # column_names_rot = 0,
            # column_names_centered = TRUE,
            column_title_gp = gpar(fontsize = unit(16, "pt"),#unit(9, "pt"),
                                   fontface = "bold")
          ),
          color = c("white", "#503080"),
          filename = file.path("test.pdf"),
          height = height, width = width)
```

