utils::globalVariables(
  c(
    "data.table",
    "sets",
    "setorderv",
    "elements",
    "rat_gene_sets",
    "elements2",
    "set",
    "set_size",
    "set_size_in_input",
    "background_size",
    "input_size",
    "p_value",
    # feature_heatmap NSE column references
    ".",
    "adj.P.Val",
    "contrast",
    "gene_symbol",
    "group",
    "sex",
    "Sex",
    "Timepoint",
    "value",
    "z"
  )
)
